file(GLOB coverage_files "${COVERAGE_DIRECTORY}/*.c.gcov")
if(NOT coverage_files)
  message(FATAL_ERROR "No coverage reports were found")
endif()

set(line_total 0)
set(line_executed 0)
set(branch_total 0)
set(branch_executed 0)
set(uncovered_lines)

foreach(coverage_file IN LISTS coverage_files)
  get_filename_component(coverage_name "${coverage_file}" NAME)
  string(REGEX REPLACE "[.]gcov$" "" source_name "${coverage_name}")
  file(STRINGS "${coverage_file}" coverage_lines)
  foreach(coverage_line IN LISTS coverage_lines)
    if(coverage_line MATCHES "^[ \\t]*[0-9]+[*]?:[ \\t]*[0-9]+:")
      math(EXPR line_total "${line_total} + 1")
      math(EXPR line_executed "${line_executed} + 1")
    elseif(coverage_line MATCHES "^[ \\t]*#####:" OR
           coverage_line MATCHES "^[ \\t]*=====:")
      math(EXPR line_total "${line_total} + 1")
      if(coverage_line MATCHES ":[ \\t]*([0-9]+):")
        list(APPEND uncovered_lines "${source_name}:${CMAKE_MATCH_1}")
      endif()
    elseif(coverage_line MATCHES "^[ \\t]*branch[ \\t]+[0-9]+")
      math(EXPR branch_total "${branch_total} + 1")
      if(NOT coverage_line MATCHES "never executed")
        math(EXPR branch_executed "${branch_executed} + 1")
      endif()
    endif()
  endforeach()
endforeach()

if(NOT DEFINED SOURCE_DIRECTORY)
  message(FATAL_ERROR "The source directory was not provided")
endif()

file(STRINGS "${COVERAGE_EXCLUSIONS}" exclusion_records)
set(excluded_lines)
foreach(exclusion_record IN LISTS exclusion_records)
  string(REPLACE "@@" ";" exclusion_fields "${exclusion_record}")
  list(LENGTH exclusion_fields exclusion_field_count)
  if(NOT exclusion_field_count EQUAL 4)
    message(FATAL_ERROR "Invalid coverage exclusion: ${exclusion_record}")
  endif()
  list(GET exclusion_fields 0 exclusion_source)
  list(GET exclusion_fields 1 exclusion_anchor)
  list(GET exclusion_fields 2 exclusion_offset)
  list(GET exclusion_fields 3 exclusion_reason)
  if(exclusion_source STREQUAL "" OR exclusion_anchor STREQUAL "" OR
     NOT exclusion_offset MATCHES "^-?[0-9]+$" OR exclusion_reason STREQUAL "")
    message(FATAL_ERROR "Invalid coverage exclusion: ${exclusion_record}")
  endif()
  set(source_path "${SOURCE_DIRECTORY}/${exclusion_source}")
  if(NOT EXISTS "${source_path}")
    message(FATAL_ERROR "Coverage exclusion source does not exist: ${exclusion_source}")
  endif()
  file(READ "${source_path}" source_content)
  string(FIND "${source_content}" "${exclusion_anchor}" anchor_index)
  if(anchor_index LESS 0)
    message(FATAL_ERROR "Coverage exclusion anchor was not found: ${exclusion_anchor}")
  endif()
  string(LENGTH "${exclusion_anchor}" anchor_length)
  math(EXPR anchor_end "${anchor_index} + ${anchor_length}")
  string(SUBSTRING "${source_content}" ${anchor_end} -1 source_after_anchor)
  string(FIND "${source_after_anchor}" "${exclusion_anchor}" duplicate_anchor_index)
  if(NOT duplicate_anchor_index LESS 0)
    message(FATAL_ERROR "Coverage exclusion anchor is not unique: ${exclusion_anchor}")
  endif()
  string(SUBSTRING "${source_content}" 0 ${anchor_index} source_before_anchor)
  string(REGEX MATCHALL "\n" source_newlines "${source_before_anchor}")
  list(LENGTH source_newlines source_newline_count)
  math(EXPR exclusion_line "${source_newline_count} + 1 + ${exclusion_offset}")
  if(exclusion_line LESS 1)
    message(FATAL_ERROR "Coverage exclusion resolves before the source file")
  endif()
  list(APPEND excluded_lines "${exclusion_source}:${exclusion_line}")
endforeach()
list(SORT uncovered_lines)
list(SORT excluded_lines)
if(NOT uncovered_lines STREQUAL excluded_lines)
  message(FATAL_ERROR
          "Coverage exclusions do not match uncovered lines: ${uncovered_lines}")
endif()

if(line_total EQUAL 0 OR branch_total EQUAL 0)
  message(FATAL_ERROR "Coverage reports did not contain executable source data")
endif()

math(EXPR line_basis_points "${line_executed} * 10000 / ${line_total}")
math(EXPR branch_basis_points "${branch_executed} * 10000 / ${branch_total}")
math(EXPR line_whole "${line_basis_points} / 100")
math(EXPR line_fraction "${line_basis_points} % 100")
math(EXPR branch_whole "${branch_basis_points} / 100")
math(EXPR branch_fraction "${branch_basis_points} % 100")
message(STATUS
        "Source coverage: ${line_whole}.${line_fraction}% lines, ${branch_whole}.${branch_fraction}% branch sites")
list(LENGTH excluded_lines exclusion_count)
message(STATUS "Reviewed coverage exclusions: ${exclusion_count}")

if(line_basis_points LESS MINIMUM_LINE_BASIS_POINTS)
  message(FATAL_ERROR "Line coverage is below the required threshold")
endif()
if(branch_basis_points LESS MINIMUM_BRANCH_BASIS_POINTS)
  message(FATAL_ERROR "Branch-site coverage is below the required threshold")
endif()
